#!/bin/bash

# Exit on any error
set -e

# Step 1: Define a function for displaying exit messages
exit_message() {
    echo "❌ Oops! There was an error during the script execution and the process stopped. No worries!"
    echo "🔄 You can try to run the script from scratch again."
    echo "🛠️ If you still receive an error, you may want to proceed manually, step by step instead of using the auto-installer."
}

# Step 2: Set a trap to call exit_message on any error
trap exit_message ERR

# Step 3: Welcome
echo "✨ This script will install your Quilibrium node as a service and start it. ✨"
echo "Made with 🔥 by LaMat (with 0xOzgur.eth help)"
echo "Processing... ⏳"
sleep 7  # Add a 7-second delay

# Step 3.1: Check if directory ~/ceremonyclient exists
if [ -d ~/ceremonyclient ]; then
    echo "🗑️ Removing existing directory ~/ceremonyclient..."
    rm -rf ~/ceremonyclient
fi

# Step 4: Download Ceremonyclient
echo "⏳ Downloading Ceremonyclient..."
sleep 1  # Add a 1-second delay
cd ~
git clone https://github.com/QuilibriumNetwork/ceremonyclient.git

cd ~/ceremonyclient/node

# Step 5: Download Binary
echo "⏳ Downloading Binary"
sleep 2  # Add a 2-second delay
wget https://github.com/QuilibriumNetwork/ceremonyclient/releases/download/v1.4.17/node-1.4.17-linux-amd64.bin
ls
mv node*.bin node

# Step 6: Make the file executable
echo "⏳ Making the Binary executable"
sleep 2  # Add a 2-second delay
chmod +x node

# Step 7: Create Ceremonyclient Service
echo "⏳ Creating Ceremonyclient Service"
sleep 2  # Add a 2-second delay
sudo tee /lib/systemd/system/ceremonyclient.service > /dev/null <<EOF
[Unit]
Description=Ceremony Client Go App Service

[Service]
Type=simple
Restart=always
RestartSec=5s
WorkingDirectory=/root/ceremonyclient/node
ExecStart=/root/ceremonyclient/node/node

[Install]
WantedBy=multi-user.target
EOF

# Step 8: Updating the node to v1.4.18
echo "⏳ Updating the node to v1.4.18"
wget -O - https://raw.githubusercontent.com/0xOzgur/QuilibriumTools/v1.4.18/update.sh | bash
