#!/bin/bash

# Step 0: Welcome
echo "✨ Welcome! This script will changed your Qnode store folder with another one for fast syncing. ✨"
echo "You must be running the node as a service, otherwise the script won't work"
echo "If you are not running as a service, follow the step by step process at https://iri.quest/qnode-store" 
echo "Made with 🔥 by LaMat"
echo ""
echo "Processing... ⏳"
sleep 7  # Add a 7-second delay

# Check if ceremonyclient service exists
if ! systemctl list-unit-files | grep -q 'ceremonyclient.service'; then
    echo "❌ The 'ceremonyclient' service does not exist."
    echo "Please make sure you are running the node as a service."
    echo "If you are not running as a service, follow the step-by-step process at https://iri.quest/qnode-store"
    exit 1
fi

# Check if zip and unzip are installed
if ! command -v zip &> /dev/null; then
    echo "🚨 Zip utility is not installed. Installing..."
    sudo apt-get update && sudo apt-get install -y zip || handle_error $LINENO "Failed to install zip utility."
    echo "✅ Zip utility installed successfully."
fi

if ! command -v unzip &> /dev/null; then
    echo "🚨 Unzip utility is not installed. Installing..."
    sudo apt-get update && sudo apt-get install -y unzip || handle_error $LINENO "Failed to install unzip utility."
    echo "✅ Unzip utility installed successfully."
fi

# Function to handle errors and exit the script
handle_error() {
    echo "❌ Error occurred in script at line: $1"
    echo "ℹ️ Error message: $2"
    exit 1
}

# Trap errors and call the handle_error function
trap 'handle_error $LINENO "$BASH_COMMAND"' ERR

# Check if store.zip already exists and overwrite if it does
if [ -f ~/ceremonyclient/node/.config/store.zip ]; then
    echo "⚠️ store.zip already exists. Overwriting..."
    rm ~/ceremonyclient/node/.config/store.zip
    echo "✅ Previous store.zip deleted successfully."
fi

# Download store from the internet
echo "🌐 Downloading store from the internet..."
wget -P ~/ceremonyclient/node/.config https://snapshots.cherryservers.com/quilibrium/store.zip
echo "✅ Download completed successfully."
sleep 1

# Stop node service if it's not already stopped
if systemctl is-active --quiet ceremonyclient; then
    echo "🛑 Stopping node service..."
    sudo service ceremonyclient stop
    echo "✅ Node service stopped successfully."
else
    echo "🟢 Node service is already stopped. Moving on..."
fi
sleep 1

# Rename store to store-original
echo "🔄 Renaming store to store-original..."
mv ~/ceremonyclient/node/.config/store ~/ceremonyclient/node/.config/store-original
echo "✅ Store renamed successfully."
sleep 1

# Extract archive in store folder without showing output
echo "📦 Extracting archive in store folder..."
cd ~/ceremonyclient/node/.config
unzip store.zip -d . > /dev/null
# unzip store.zip -d store > /dev/null - this creates a nested store/store folder
echo "✅ Archive extracted successfully."

# Delete store.zip and store-original
echo "🗑️ Deleting store.zip and store-original..."
rm ~/ceremonyclient/node/.config/store.zip
echo "✅ store.zip deleted successfully."
rm ~/ceremonyclient/node/.config/store-original
echo "✅ store-original deleted successfully."
sleep 3

# Restart node service
echo "🔄 Restarting node service..."
service ceremonyclient start
echo "✅ Node service started successfully."

echo -e "\n📜 I will now show the node log (CTRL+C to detach)"
echo ""
echo ""

# Show node log
sudo journalctl -u ceremonyclient.service -f --no-hostname -o cat
